language: php

before_script:
  - sudo apt-get update
  - sudo apt-cache search swftools
  - sudo apt-get install -y swftools
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

php:
  - 5.3
  - 5.4

